import { addNumbers, fillGrid, Grid, readLinesSplit, say } from '../../utils';

/*
 * The number of steps to take is 26 501 365, which "coincidentally" ends exactly on the edge of a garden, which
 * simplifies things, and we can use some geometry to find a formula.
 * Each reachable garden plot will be contained inside a square rotated 45 degrees relative to the gardens.
 * Each garden has 131 x 131 plots.
 * Let's start by looking at the center garden. After all plots in this garden have been reached, the currently visited
 * plots in the garden changes between two different states, depending on whether the number of steps is odd or even.
 * The same applies to the other gardens. The number of reachable plots in a garden (after a given number of steps)
 * where all reachable plots have been visited is 7566 or 7509 (numReachablePlotsForGardensInState1 /
 * numReachablePlotsForGardensInState2) - depending on whether the total number of steps is odd or even. Since the x and
 * y size of the garden is an odd number (131), adjacent gardens have opposite states. A drawing can reveal how to count
 * the number of visited garden plots in edge gardens after the final step is taken.
 * See bottom of file to see one garden where all the garden plots are marked that can be reached in exactly 65 steps.
 */

const gridSize = 131;
const numSteps = 26_501_365;
const numGardensInOneDirection = (2 * numSteps + 1) / gridSize;
const numState1Gardens = Math.pow((numGardensInOneDirection - 1) / 2, 2);
const numState2Gardens = Math.pow((numGardensInOneDirection + 1) / 2, 2);

const [
  numReachablePlotsForGardensInState1,
  numReachablePlotsForGardensInState2,
  numReachablePlotsForHalfGardensInState1,
  numReachablePlotsForHalfGardensInState2
] = calculateNumReachableGardenPlots();

const numTimesExpanded = Math.sqrt(numState2Gardens) - 1;
say(addNumbers([
  numState1Gardens * numReachablePlotsForGardensInState1,
  numState2Gardens * numReachablePlotsForGardensInState2,
  numTimesExpanded * numReachablePlotsForHalfGardensInState1,
  -(numTimesExpanded + 1) * numReachablePlotsForHalfGardensInState2,
]));

function calculateNumReachableGardenPlots(): [number, number, number, number] {
  let [numReachablePlotsForGardensInState1, numReachablePlotsForGardensInState2] = [0, 0];
  let [numReachablePlotsForHalfGardensInState1, numReachablePlotsForHalfGardensInState2] = [0, 0];

  const shortestPaths = getShortestPathsToPlotsInCenterGarden();

  for (let y = 0; y < gridSize; y++) {
    for (let x = 0; x < gridSize; x++) {
      if (shortestPaths[y][x] === Infinity) {
        continue;
      }

      if (shortestPaths[y][x] % 2 === 0) {
        numReachablePlotsForGardensInState1++;
      } else {
        numReachablePlotsForGardensInState2++;
      }
      const midPos = Math.floor(gridSize / 2);
      const distanceFromCenter = Math.abs(y - midPos) + Math.abs(x - midPos);
      if (distanceFromCenter > midPos) {
        if (shortestPaths[y][x] % 2 === 0) {
          numReachablePlotsForHalfGardensInState1++;
        } else {
          numReachablePlotsForHalfGardensInState2++;
        }
      }
    }
  }

  return [
    numReachablePlotsForGardensInState1,
    numReachablePlotsForGardensInState2,
    numReachablePlotsForHalfGardensInState1,
    numReachablePlotsForHalfGardensInState2,
  ];
}

function getNewPositions(gardenPlots: string[][], y: number, x: number): [number, number][] {
  const positions: { [key: string]: boolean } = {};
  if (canGoTo(gardenPlots, y-1, x)) {
    positions[`${y-1},${x}`] = true;
  }
  if (canGoTo(gardenPlots, y+1, x)) {
    positions[`${y+1},${x}`] = true;
  }
  if (canGoTo(gardenPlots, y, x-1)) {
    positions[`${y},${x-1}`] = true;
  }
  if (canGoTo(gardenPlots, y, x+1)) {
    positions[`${y},${x+1}`] = true;
  }
  return Object.keys(positions).map((posStr) => {
    const [yStr, xStr] = posStr.split(',');
    return [parseInt(yStr), parseInt(xStr)];
  });
}

function canGoTo(gardenPlots: string[][], y: number, x: number): boolean {
  return y >= 0 && x >= 0 && y < gridSize && x < gridSize && gardenPlots[y][x] === '.';
}

function getShortestPathsToPlotsInCenterGarden(): Grid {
  const gardenPlots: string[][] = [];
  let currentPositions: [number, number][] = [];

  readLinesSplit('input.txt', '').forEach((lineArray: string[], y) => {
    if (lineArray.includes('S')) {
      currentPositions.push([y, lineArray.join('').indexOf('S')]);
      lineArray = lineArray.join('').replace('S', '.').split('');
    }
    gardenPlots.push(lineArray);
  });

  const shortestPaths = fillGrid(gridSize, gridSize, Infinity);
  for (let i = 0; i < 150; i++) {
    const newCurrentPositions: { [key: string]: boolean } = {};
    currentPositions.forEach(([y, x]) => {
      getNewPositions(gardenPlots, y, x).forEach(([y_, x_]) => {
        newCurrentPositions[`${y_},${x_}`] = true;
        if (shortestPaths[y][x] === Infinity) {
          shortestPaths[y][x] = i;
        }
      });
    });
    currentPositions = Object.keys(newCurrentPositions).map((posStr) => {
      const [yStr, xStr] = posStr.split(',');
      return [parseInt(yStr), parseInt(xStr)];
    });
  }
  return shortestPaths;
}

/*
Reachable garden plots after 65 steps marked with O:
.................................................................O.................................................................
....#...#.......................#.#......###..#.............#...O.O..........#.....#.....#.#...#.........#.#..........#......#.....
...#.##.#...#.....................#.......#.......#....#.......O.O.O.......#....#...........#.#...........#....#...#...............
.#........#.#................#.....#.....#.........#..........O.O.O.O......#..#...#........#..#..........##............#...........
.....#.#.....#.....#..........#........#.........#...#.......O.O.O.O.O..........#....#.#......#....#.#####.................#.#.....
...........................#...........#...#..#...#.........O.O.O.#.O.O...#......#.#......#.......#.......#.........#.........#....
......#...#.....##.......................#.................O.O.#.O.O.O.O......#..#...##...#....#....##....##....#..#...............
..................#...........#...........................O.O.O.#.O#O.O.O..................#....#.....#................#...........
.#....##......#.............#.#.....#...#..#...#.....#...O.O.#.O.O.#.#.O.O......#..##..........#.........#.........................
...........#.......#.....#................#.....#.......O.O.O.O.O.O.O.O.O.O....#.#....#...............#..........................#.
............#.#..............#.......#.................O.O.O.O.O.O.O.O.O.O.O.............#......##....#.......#...##...............
...................#.#......#.....................#...O.O.O##.#.O.O#O.O#O.O.O.......#...................#.....##.....#..#.#..#...#.
..........#......#...#...#..#.................#......O.O.O.O.#.O.O.O.O.O.O.O.O.....#.........#.#........#.......#.#..............#.
......#.......#...#.#............#.....#.#..........O.O.O.O.O#O.O.O.O.O.O##.O.O...................#...#...##......#..#......#......
.#.............#.....#......#.....#.........#......O.O.O.O.##O.O.O.O.O.O.O.O.O.O...............#..#..#.#........#.....#............
......#...............#......#....................O.O.O.O.#.O.O.O.O.O.O.##O.#.O.O.....##.........#.#......#......#..............#..
.........#..............#........................O.O.O.O.O.#.O.O.O.O.O.O.O.O.#.O.O......##.......#........#........##............#.
.....#..........#.....#.#..................##...O.O.O.O#O.O.#.O.O.#.O.#.O.#.O#O.O.O...#.............##.......#.....#........##.##..
......#........#.....................#.........O.O.O.O#O.O.O.O.O.O.O.O.O.O.O.#.O.O.O.....#...#......#...##.........................
..............#................#..#...........O.O.O.O.#.O.###.O.O.O.O.O.O.O.O.O.O.O.O.......#.#..##........##......##...#.....#....
....#...............##.....#.#........#......O.O.O.O.#.O#O.O.O.O#O.#.O#O.O.O.O.#.O.O.O......#..##....#......#.....###..............
.#......................#..#...#....#.......O.O.#.O.#.O.O.O.O.O.O.O.#.O.O.O.O#O.O.O.O.O...#...#.##....#................##....#...#.
......#.......#.#...#......##..............O.O.O.O#O.O.O.O.O.O.O.O#O.O.O.#.O.O.O.O.O.O.O.......##.....#.#.....##.................#.
......##................#....#...#...#....O.O.O.O.O#O.O.O.O.O.O.O.O.O.#.O.O.O.O.#.O.O.O.O.......#...........##.................#...
....#.....#...#.#....#....#.......#.#....O.O.O#O.O###O.O.O.O.#.O.O.O.O.#.O.O.O.O.O.O.O.O.O...#.....#.##...#..##......#...#.........
.................#....#...#....#.#......O.O.O.O.O.O.O.O.#.O.O.O.O.O.#.O.O.#.O.O.#.#.##O.O.O...#..........#......#..#....#..........
....#...........#.......#..............O.O.O.#.#.O.#.O.O.O.O.#.O.O.O.O.O.O.#.O#O.O.O.O.O.O.O.....##............#.#.................
...................#.#.......#...##...O.O.O.O.O#O.O.#.O.O.O.O.O.#.O.O.O.#.O.O.O.O.O.O.O.O.O.O....#...........#.##....##....##......
......#..#.#...#..............#......O.O.O.O.O.O.O.O.O.O.O.O.O#O.O.O#O#O.O.O.O.O.O.O#O.#.O.O.O......#........#..............#.#....
..#....#...........#...##..##..#....O.O.#.O#O.O.O#O.O.#.O.#.O.#.O.#.O.O#O#O.O.O.O.O.O.O.O.O.O.O.......#.#.#........................
......#................#.#.........O.O.O.O#O.#.O.O##.O.O.O.O#O.O.O.O.#.O.O#O.O#O.#.#.O.O.O#O.O.O.....##....#...#......#.#.#...#..#.
...#.#..##..#......#..............O.O.O.O.#.O.O.O.O.O.O.O.O#O.O.O.O.O.O.O.O.O.O.#.O.O.O.O.O.O.O.O............##...#......#..#......
....#...#.##...##.......#........O.O.O.O.#.#.O#O.O.O.O.#.#.O.O.O.O.O.O.#.O.O.O.O.O.O##.#.O.O.O.O.O................##......##.......
...#.........###.#.....#........O.O.#.O.O.O.O.#.O.O.O.O.O.O.O.O#O.O.O.O.O.O.O.#.O.O.O.O.O.O.O.O.O.O........#......#.....#..#.......
...###....#....................O.O.O#O.#.O.#.O.O.O.O.O.O.O.O.O.O.O.O.O.O#O.O.O##.O#O.O.O.O.O.#.O.O.O.....#.....#................#..
.............##.....#.........O.O.O.#.O.O.O.O.O#O.O.O#O.O.O.O.O.O.O#O.#.O.#.O#O.O.O.O.#.#.#.O.O.O.O.O...#............#...........#.
.......#..........#..........O.O.#.O.O.O.#.O#O.O.O.O.#.#.O.O.O.O.O.O.O.#.O.O.O.O.O.O.O.O#O.O.#.O.O.O.O.......#.....................
.............#..#...........O.O.O.O.O.##O.O.O#O#O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O#O.#.O#O.#.O.O#O.O##.O.O........#..#......#.........
................#...#.#....O.O.O.O.O#O.O.O.O.O.O.#.O.O.O.O.O.O.O.O.O.O.O.O.O.#.O.O.O.O.O.##O.O#O.#.O.O.O....#.......#..#........#..
.........#.#.........#....O.O.O.O#O.O.O.O.O#O.O.O.O.O.#.O.O.O.O.O.#.O.O.O.O.O.O.#.O.O.O.O.O#O.O.O.O.O.O.O.....#...#....#....#..#...
...#.#.....#...#.........O.O.O.#.O#O.O.O.#.O.O.O.##O.O.O.O.#.O#O.O.O.#.O#O.O.O#O.O.O.O.O.#.O.#.#.O.O.O.O.O...#...#....#.....#......
..#...#..##.....#.......O.O.O#O#O.O.O.#.O.#.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O#O##.O.O.O.O.O.O.###.O.O#O.O.O.O.........##....#......#.
.......................O.O.O.O.O.O.#.#.O.#.O.O.O.#.O.O.##O.O.#.#.O.O.O#O.#.O.O.O.O.O.O.#.O.O.O.O.O.#.O#O.O.O...#.................#.
.......#..............O.O.#.O#O.O.O.O.O.O.O.O.#.O.O.O.O.O.O.O.O.O.O.O.O.#.O.O.O.O.O.O.O.O.#.O.O.O.O.O#O.#.O.O.................#....
..........#...#.##...O.O.O.O.O.O.O.O#O.O.O.##O.##O.O.O.#.O.O.O#O.O.O.#.O##.O.O.#.O.O.O.O.O.O.O#O.O.#.O.O.O.O.O...#...#..##.#...#...
................#...O.O.O.O.O.O.O.O.O.O.O.#.O.O.O.#.O.O.O.O.O.O.O.#.O.O.O.#.O#O.O.##O.O#O.O.O.#.O.O#O.O.O.O.O.O.....#............#.
..#....#..##.#.....O.O.O.#.O.O.O.O.##O.#.O#O.#.O.O.O.O.O.O.O.O.##O.O.O.#.O.##O.O.O.O.O.O.O.O.O.##O.O.#.O.O.O.O.O.....#.#..##.......
......#......#....O.O.O.O#O.O.#.O.#.O.O#O#O.O.O.O.O.O.O.O.O.O.O.#.O.O.O.O.O.#.O.O.O.O.O.O.O.O#O.O.O.O.O#O#O.O.O.O...#.#............
.....#....#..#...O.O.##O.O.O.O.O.O.O.O.O.O.#.O.O.O.O.O.O.O.O#O.O.O.O#O.O.O.O.O.O#O.O.O.O#O.O.O.O.O.O.O.#.O.O.O.O.O........#........
..#........#....O.O.#.#.O.O.##O.O.O.O.#.O#O.O.O#O.O.O#O.O.O.#.O.O.O#O#O.O.O.O.O.O.##O.O.#.O.O.O.O.O.O.O#O.O.O.O.O.O...#...#........
..#.##.........O.O.O.O.O.O.O.O#O.##O#O.O.O.O.O#O.O.O#O.O#O.O.O.O.O.O.#.O.O.O.O.O.O.O#O.O#O.O.O.O.O#O.O.O.O.O.O#O.O.O.......##......
...#..........O.O.O.O.O.O.O.#.#.O.O##.#.O.O.O.#.#.O.O.O.O.O.O.#.O.O#O.O#O.O.O.#.O.O.#.O.O.#.O#O.O.O.#.O.##O.O.O.O.O.O....#.........
......#......O.O.O#O.O.O.O.O.O.O.O.O#O.O.O.#.#.O.O.O#O.O.O.O##.#.O.O.#.O.O.#.O.O.O.O.O.O.O#O.O.O.O.O.O.O.O.O.O#O.O.O.O.......#.....
.......#....O.O.O.O.O.#.O.O.O.O.O#O.O.O.O.O.#.O.O.O.O.O.#.O.#.O.O.O.O.O.O.O.O.O.O.O.O#O.#.O.O#O.O.O.O.O.O.O.O.O.O.O.O.O...#....#...
...........O.O.O#O.#.O.O.O.#.O.O#O.##O.O.O.O.O.O.####O.O.#.O#O.O#O.O.O.O.O.O.O.O.#.O.O.O.O.O.O.O#O.O.O.O.O.O.O.O.O.O.O.O.........#.
...#..#...O.O.O.O.O#O.#.O.O.O.O#O.O.O.O#O.O.O.#.O##.O.O.O.O.O.O.O.#.O#O#O.O#O.O.O.#.O.O.O.O.#.O.O.O.O.O.O.O.O.#.#.O.O.O.O...#.#....
..#......O.O.O.O.O#O.O#O.O.O.O.O.O.O.O.O.O.O.O.O.#.#.O.O.O.#.O#O.O.O.O.O.#.O.#.O.O.O.#.O#O.O.#.#.O.O.O.O.O.O.O.O.O.O.O.O.O....#..#.
...#....O.O.O.O.O.O.O.O.O.O.O.O.O.O.#.O.#.O.O.#.O.#.O.O.O.O#O.O.O.O#O.#.O#O.O.O.O.O.O.O.#.O.#.O.O.#.O.O.O.#.O.O.O.O.O.O.O.O........
.......O.O.O##.O.O.O.O.O.O.#.O.O.O.#.O.O.O.O.O.#.O.##O.O.O.#.O.O.O#O.O.O.O.O.O.O.O.O#O.O.O.O###O.O.O.O.O.O#O.O.O.#.O.O.O.O.O.....#.
......O.O.O.O.O.O.O.O.O#O.O###O.O.O.O.O#O.O.O#O.O.O.O.O.O.O.O.O#O.O.##O.#.O.O.O.O.O.O#O.O.O.O.O.O##.O.O#O.O.O.O.O#O#O.##O.O.O......
.....O.O.O.##O.O.O.O.O.O.O.O.O.O.O#O.O.#.O#O.O.O.O.O.O.O.O.O.O.#.O.O.O.O.O.O.O.O.O.O.#.O.O.O.O.O#O.O.O##.O.O.O.O#O.O.O.O.O.O.O...#.
....O.O.#.O.O.O.O#O.O.O##.O.O.O.O##.O.O.O.O.##O.#.#.O.O.O.O.O.O.O.O.O##.O.O.O.O.O##.O.#.O.##O.O.O.O.O.O.O.#.O.O.O#O.O.O.O.O.O.O....
...O.O.O.O.O.O.O.O.#.O.O.O.O.#.##O.#.O#O#O.#.O.O.O.O.O.##O.O.O.O.O.O.O.O.#.O.O.O.#.O.O.O#O.O#O#O.O.O.O.#.#.O#O.O.O.O.O.O.O.O.O.O...
..O.O.O.O.O.O.O.O#O.O.O.O.O.##O.O.O.O.O.O.O#O.O.O#O.O.O.O##.O#O.#.O.O.O.##O.##O.O.O.O.O.O.O.O#O.O.O.O.O.O.O.#.O.O.O#O##.O.O.O.O.O..
.O.O.O.O.O.O#O.O.#.O.O.O.O.O.O.##O.O#O.O.O#O.O.O.O.O.O.O.O.O.###.O#O.#.O.O.O#O.O.O.O.O.O.#.O.O.O.O.O.O##.O.O.O.O.O.O.O#O.O.#.O.O.O.
O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O
.O.O.O.O.O.O#O.O.O.#.O.O#O.O.O.O.#.O#O.#.#.O.O.O.O.O.O.O.O.O#O.#.O.O.O#O.O.O.O.O.O.O.O.#.O.O.O.O.O.#.#.O#O.O.#.O.O.O#O.#.O.O.#.O.O.
..O.O.O.O.O.O.O.#.O.O.O.O.O.O.O.O.O.O.O.#.O.##O.O.O.O.O#O.O.O.O.O.O.O.O#O#O.O.O.O.O.O.O.O.O.O##.O.O.O.O.#.O.O#O.#.O.O.O.O.O.#.O.O..
...O.O.O.O.#.O##.O#O.O.O.O.O.O#O.O.O.O.##O.O.O.O.O.O#O.##O.#.O#O.O.O.O.O.#.O.O.O#O.O.O.O.O.#.O.O#O.#.O.O.O.O#O.O.O.O.O##.O.O.O.O...
....O.O.O##.O#O.O#O.O.O.O.O.O.O#O.O.#.O.O.O.O.O.#.O.#.O.#.O.O.O#O.#.O.O.O.O.O.O.O.#.O.O.O.O#O.O.O.O.O.O.O.#.#.O.O#O.O.O.O.O.O.O....
.#...O.O.O.O.O.O.O.O.O.O.O.O.O#O.O.O.O.O.O.O.#.O.O##.O.O.#.O#O.#.O.O.O.O.O.O#O#O.O.#.O#O.O.O.#.O.O.#.O.O.O.O#O.O.O#O.O.O.O.O.O.....
......O.O.O.O.O.O.O#O.O#O.O.O.O.O.O#O.O.O.O.O.O.#.O.O.##O.O.O.O.#.O.O#O.O.#.O#O.O.#.O.O.O.O.#.#.O.O#O#O.O.O##.O#O.#.O.O#O.O.O......
.......O.O.O.O.O#O#O.O#O.O.#.#.O.O##.O#O.##O.O#O.O.O.O#O#O.O.O.O.O.O.#.O.O.O.O.O.O.O.O.O.O.O.O.###.#.O.O.O.O.O.O.O.O.##O.O.O.......
.#.#....O.O.O.O.O.O.O.O.O.O.O#O.O.O.O.O.O.O.O.O.O.O#O.O.O.O.O.O.O.O.O.O.O.O#O#O.O#O.##O.O#O.#.#.O.O.O.#.O.O.O.O.O.O.O.#.O.O...#..#.
.........O.O.O#O.O###O.O.O.O.O.O#O.O.#.O#O.O.O.O.O.O.O.O.O#O.#.O.O.O#O#O.O.O.O.#.#.O.#.O.#.O#O.#.O.#.#.O#O.O.O.O.O.O.O.O.O....#.#..
..........O.O.O.O.O.O.O.O.O.O.O.O.O.O##.O.O.O.O.O.O.O.#.#.O.O.O.#.O.O.O.#.O.O.O.O.O#O.O.O.#.O.O.O.O.#.O#O.O.O.O.O.O.#.O.O..........
...........O.O.O.O.O.O#O.#.#.#.O.O.O.O.O.#.##O.O.O#O.O.O.O.O.O.O.O#O.O#O.O.O.O.O#O.O.O##.O.O.O.O.O.O##.O.O.O.O.O.O.O.O.O....#....#.
............O.O.O.O#O.O.#.O#O#O.O#O.O#O.O.O#O.O.O.O.O#O.#.O.O.O.#.O.O.O.O.O.#.O#O.O.O.O.O.O.O.O.O.O.O.#.O.O.O.#.O.O.O.O...#........
.............O.O.O.O.#.O.#.O.O.#.#.O.O.O#O.O.##O.##O##.O.O.O.O.#.O.O.O.O.O#O.O.O.O.O.O###O.O.O.#.O.O.O#O.O.O.O#O.O.O.O........#....
..#...........O.O.O.O.O.#.O.O.O.O.O.O.O#O#O.#.O.O.O.O.O.O#O.O.O#O.O.O.O.O#O#O.O.O.O.O.O.O.#.O.O.O.O.O.O.O.O.O.O.O.O.O......#.......
.#........#....O.O.O.O##.O.O.O.O.O.O.O.O.O.O.O.O.O.#.O.O.O.O#O.O.O.##O.O.O.O.O.O.#.O.O.O#O.O.O.#.O.O.O#O.O.O.O.O.O.O...............
...........#....O.O.O.O.O.O.O.O#O.O##.O.O.O#O.O.O.O.O.O#O.O.O.O.O.O.O.O.O.O#O.O.O.O.O.O.O.O.O.O#O#O.O.O.#.O.O.O.O.O...#..#...#.....
..........#......O.O.##O.O.O.O.##O.#.#.O.O#O.O.O#O.O.O.O.O.O##.O.O.O.#.O.O.O.O.O.#.O.O.O.##O#O.O.O.O.#.O.#.O.O.O.O....#..........#.
.........#........O.O.O.O.O.O.O.O.O.O#O.O#O##.O.O.O.O.O.#.O.O.O.O.O.O.##O.O.#.O.#.O.#.O.O.O.O.O.O.#.O.O.#.O.#.O.O.....#............
..#.....#..........O.O.O.O.O.O.O.O.O#O.O.#.O.O.O.O.O.O.O.O.#.O#O.O.O.O.O.O.O.O.O.O.##O.#.##O##.O.O#O.O.O.#.O.O.O............#......
.....##.............O.O.O.#.O.O.O#O#O.#.O.O.O.O.O.O.#.O.O.O.O#O.O.O.#.O#O.O.O.O.O.O.O.O.O.O.O.O.O#O.O.O.O.O.O.O.......#....#...#...
.#...................O.O.O.O.O.O.O.O.#.O.O#O.O.O.O.#.O.#.#.O.#.O.O.O.O.O.#.#.O.O.O.#.O#O.#.O.O.O.##O#O.O.O.O.O..........#....#.#.#.
.#......#....#....#...O.O.O.O.O.O.O.O.O.O.O#O.O.O.O.O.O.O.O.O.O.#.O.#.O#O.O#O.#.O.O.O.O.O.#.O.O.O#O.#.O.O.O.O......................
..........#.......#....O.O.O.#.O.O.O.O.##O.O##.O.O.#.O.O.O.#.O.O#O.O.O.O.O.#.O#O.O.O.#.O.O.O.O.O.O.O.O.O.O.O............##.........
...#...........#........O.O.O.O#O#O.O.##O.O.O.#.O.O.O.O.O.O.O.O.O.O.#.O.O#O.O.O.O.O.##O.#.O##.O.O##.#.O.O.O...#......#.......#.....
.#.................#.....O.O.O.#.O.O.O#O.O#O.O.O.O.#.O.O.O.O.#.##O.O.O.O.O.O.O.#.O.O.O.#.O.#.#.O.#.O.#.O.O......#..#.#.............
.....#..#...#...#.........O.O.O.O.O.#.O.#.O#O.#.O.O.O.#.O#O.O.O.O.O.O.O.O.#.O.O.O.O.O.O#O.O.O.#.O.O.O.O.O.........##..#..........#.
......#.......#...#........O.O.O.#.##O.O.O#O.#.O.O.O.O#O.O.#.O.O.O.O.O#O.###.O.O.O.O.O.O.O.O.O.O.O.O.O.O.......#............#......
..#..........#...#..##..#...O.O.O.O.##O.O.O.O.O##.O.O#O.#.O.#.O.O.O.O.O#O##.O.O.O.#.O.O.O.#.O#O.#.O.O.O......#.#...#.......##..#...
..#..#....#..##........##....O.O.O.O#O#O.O.O.O.O.O.O.O.O.#.O.O.O#O#O#O.O.O.O.#.O.O.O.O.O#O.O.O.O.O.O.O....................#..#.....
.................#............O.O.O.O.O.O.O.O#O.#.O.O.O.O.O.O.O.O.O.O#O.#.#.#.O#O.O.#.O.O#O.O.O.O.O.O...#....###.....#...#..##.#...
......#.....#.........#........O.O.O.O.O.O.O.O##.O.O.#.O.O.O.#.#.O##.O.O#O.O.O#O.O.#.O.##O.O#O.#.O.O......#....#..#................
..........#........##...........O.O.O.O.O.O.O.O.#.#.O.O.O.O.O#O.O.O.O.O.O.O.O.#.O.O.#.#.O.##O.O.O.O................#.......#..#....
.........#.....#...........#.....O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.....#.....#...............#.....
.................#.....#..........O.O.O.O.#.O.#.O.O#O#O.O.O.O.O.O.#.O##.O.O.O.O.O#O.O.O.#.##O.O.O........###......#..........#.....
.#.................................O.O.O.O.O.O.O.O.O.#.O#O.#.#.O.O.O.O#O.O.O.O.O.O.O.O#O.O.O.O.O...........#.............#..#......
..#..#......#..#........#..#........O.O.O.##O.O.O.O.O.O#O#O.O.O.O.#.O.O.O.O.#.O#O.O.O.O.O.O.O.O.....................#.....#........
.#.....#..#.#..##....#...#...........O.O.O.O.O.O#O.O.O.O.O.###.#.O##.O.O.O.#.O.O.O.O.O.O.O.O.O.......#....#........#..#............
..#.......#.#.......#........#.#......O.O.O.O#O.O.O.O.O.#.O.O.O.O.#.O.#.O.O.O.O.O.O.O.O.O.O.O...............#........#.##.......#..
...#......#.#......##.##......##.#.....O.O.O.##O.O.#.O.O.#.O.O.O.O.O.O.O.O.O.O.O#O.O.O.O.O.O....#.....##.............#..........#..
.#.#....#...............................O.O.##O.O.O.O.O.O.O.O.O#O.O.O.O.O.O.O##.#.O.O.O.O.O......#...#.#...#.............#.....###.
..#..........#.##.###....#...#.......#...O.O.O.O.O.O#O.O.O.O#O.O.O.O.O.O.O.O.O#O#O.O.#.O.O......#.#...#...#..#........#............
.......##.........#....#....##..##........O.O.##O.O.O.O.O#O.O.O.O.O.O#O.O##.#.O.O.##O.O.O.....#.........#............#.#....#.##...
....#...###...........#......#.............O.O.#.O.O.#.#.O.O.O.O.O.O.O.O.#.O.O.O.O.O.O.O...#......#.............................#..
...#..#...................#..#....#...#.....O.O.O.O.#.O.O.O.#.#.O.O.O.O.###.O.#.O.O.O.O...........#....##..#...........#......#....
.#...............#.............#..##.........O.O.O.O.O.O.O.O.O.O#O.O.O.O.O.##O.O.O.O.O........#.#.#.##....#.......#.#...#..#.......
..#...........#.....................#..#......O.O.O#O.#.##O.#.O.O.O####.O.O.O.O.#.O.O..........................##........###.##.#..
.......#.....#..........#.#....................O.O.O#O.O.O.O.O.O#O.O.O#O.O#O.O.#.O.O..........#..........##.#................#.....
.#.....#....#...#....#..........#...............O.O.O#O.O.O.O.O.O.O.O.#.O.O#O.O.O.O....#....#.....................##...#....#....#.
................##...#....#........#..##.........O.O.#.O.O.O.O.O.O##.#.O.O##.O.O.O......#........#.##............#.#.........#.....
......#.#.#.#....#........................#.......O.O.O.O.O.O#O#O.O.O.O.O.O.O.O.O.......#........#.#....................#.....#.#..
......#..#.........#........#....#...#...#...#.....O.O.O.O.O.##O.O.O.O#O#O.O.O.O......................................##...#....#..
......#.#......................#....#..#............O.O.O.O.#.O.O.O.#.O.O.O.O.O......#..#..#.#..#...............#.........##.#.....
............#.....................###................O.O.O.O##.O.O.#.O.O.#.O.O....#...#........#.........#..#........#.........#.#.
....#......#..#.................#........#..#...#.....O.O.#.O.O.#.#.O.O.O.O.O.......#.............#..#.....#........#....#.........
.#..#......#..#.....................#.....#......#.....O.O.O.O.O.O.O.O.O.O.O....#..#..................#..#..##...........#.........
...#.............#...........#...................#.#....O.O.#.O.O.#.O.O.O.O....#............................#..#...................
.....#....#.........#..#.#..............#.#..#.##....#...O.O.##O.O.O.O.O.O...............#....#...........#...............###......
......#................#..#....................#.....#....O.O.O.O.O.O.O.O.....#.#....#.......#................#.............#...#..
..........#...........#.........#.................#........O.O.O.O.O.O.O....#........#..#.............#......#..........#..#.......
.....#...#...................#.....#.........##..#..........O.O.O.O.O.O................#.....#.#....#........#...#..#....#.........
..#.#.......#...##..#........#..##...##.#...#...........#....O.O.O.O.O............#.....#........#..................#....#.....#.#.
.#.........................#.............#....................O.O.O.O............#..........##....#..#####.#.#.................#...
.#.#...........#.....#.##.....#...............#....#.....#.#...O.O.O.........#..#.....#...#...........#......#...#............#..#.
...#...........#..#............#.......#.#.........#..##........O.O.....#.#.......#............#.................#.....##..........
.................................................................O.................................................................
*/
